#ifndef CUSTOM_MESSAGE
#define	CUSTOM_MESSAGE

#define WM_USER			0x0400
#define	WM_DISPLAY_TEXT			(WM_USER + 0x102)
#define	WM_CLIENT_CONFIG		(WM_USER + 0x106)
#define	WM_SERVER_CONFIG		(WM_USER + 0x107)

#endif
