#ifndef CUSTOM_MESSAGE
#define	CUSTOM_MESSAGE

#define WM_USER			0x0400
#define	WM_GET_IP_BY_NAME_DONE	(WM_USER + 0x102)
#define	WM_GET_HOST_BY_IP_DONE	(WM_USER + 0x103)
#define	WM_GET_SERVICE_BY_PORT	(WM_USER + 0x104)
#define	WM_GET_PORT_BY_SERVICE	(WM_USER + 0x105)
#define	WM_CLIENT_CONFIG		(WM_USER + 0x106)
#define	WM_SERVER_CONFIG		(WM_USER + 0x107)

#endif
